# Registers the AI Bridge native-messaging host for Chrome (current user).
# Usage:
#   powershell -ExecutionPolicy Bypass -File install.ps1 -ExtensionId <id>
#   powershell -ExecutionPolicy Bypass -File install.ps1 -ExtensionId <id> -Port 8765 -ApiKey mysecret -NoKeepAlive
# Find <id> at chrome://extensions (Developer mode) under "AI Bridge (dev)".
param(
  # Fixed ID — the manifest pins it via "key", so it's the same on every machine.
  # Override only if you changed the manifest key.
  [string]$ExtensionId = "pfjfedifpkebijefjfoliofcjkipkpnd",
  [int]$Port = 8765,
  [string]$ApiKey = "",
  [switch]$NoKeepAlive
)

$ErrorActionPreference = "Stop"
$dir = $PSScriptRoot
$bat = Join-Path $dir "aibridge-host.bat"
$mjs = Join-Path $dir "aibridge-host.mjs"
$manifestPath = Join-Path $dir "com.aibridge.host.json"

if (-not (Test-Path $mjs)) { throw "Missing $mjs" }
if (-not (Get-Command node -ErrorAction SilentlyContinue)) { throw "Node.js not found on PATH" }

# Generate the launcher with config baked in (Chrome-spawned host inherits these env vars).
$keepalive = if ($NoKeepAlive) { "0" } else { "1" }
$batLines = @(
  "@echo off",
  "rem Generated by install.ps1 — native-messaging launcher for AI Bridge.",
  "set AIBRIDGE_PORT=$Port",
  "set AIBRIDGE_KEY=$ApiKey",
  "set AIBRIDGE_KEEPALIVE=$keepalive",
  "node ""%~dp0aibridge-host.mjs"" %*"
)
Set-Content -Path $bat -Value $batLines -Encoding ascii

$manifest = [ordered]@{
  name            = "com.aibridge.host"
  description     = "AI Bridge local HTTP API host"
  path            = $bat
  type            = "stdio"
  allowed_origins = @("chrome-extension://$ExtensionId/")
}
$manifest | ConvertTo-Json | Set-Content -Path $manifestPath -Encoding utf8

$reg = "HKCU:\Software\Google\Chrome\NativeMessagingHosts\com.aibridge.host"
New-Item -Path $reg -Force | Out-Null
Set-ItemProperty -Path $reg -Name "(default)" -Value $manifestPath

Write-Host "Installed AI Bridge host."
Write-Host "  manifest : $manifestPath"
Write-Host "  launcher : $bat"
Write-Host "  extension: $ExtensionId"
Write-Host "  port     : $Port"
Write-Host "  api key  : $(if ($ApiKey) { 'set (send header x-aibridge-key)' } else { 'none (localhost only)' })"
Write-Host "  keepalive: $(if ($NoKeepAlive) { 'off (lower idle cost; first call may be slow)' } else { 'on (always ready)' })"
Write-Host ""
Write-Host "Next: reload the extension at chrome://extensions, then test:"
Write-Host "  curl http://127.0.0.1:$Port/health"
