# Removes the AI Bridge native-messaging host (current user).
# Usage:  powershell -ExecutionPolicy Bypass -File uninstall.ps1
$ErrorActionPreference = "SilentlyContinue"

$reg = "HKCU:\Software\Google\Chrome\NativeMessagingHosts\com.aibridge.host"
if (Test-Path $reg) { Remove-Item -Path $reg -Force -Recurse; Write-Host "Removed registry key: $reg" }
else { Write-Host "Registry key not found (already removed): $reg" }

# Delete the machine-specific files generated by install.ps1 (safe to remove; regenerated on install).
$dir = $PSScriptRoot
foreach ($f in @("com.aibridge.host.json", "aibridge-host.bat")) {
  $p = Join-Path $dir $f
  if (Test-Path $p) { Remove-Item -Path $p -Force; Write-Host "Deleted $p" }
}

Write-Host ""
Write-Host "Native host removed. To finish removing AI Bridge:"
Write-Host "  - chrome://extensions -> AI Bridge (dev) -> Remove"
Write-Host "  - (optional) delete this repo folder"
